name: Deploy Laravel to StackCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repositori
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup PHP untuk Laravel
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # Sesuaikan dengan versi PHP di StackCP
          extensions: mbstring, bcmath, zip, pdo, mysql

      # Install dependensi Composer
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      # Buat file .env dari GitHub Secrets
      - name: Create .env File
        run: |
          echo "${{ secrets.ENV_FILE }}" | base64 --decode > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      # Deploy ke StackCP menggunakan SSH
      - name: Deploy to StackCP
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ssh.gb.stackcp.com
          username: ternakpro.id
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/sites/2b/5/535431543a/public_html/ternakpro_backend
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan config:clear
            php artisan cache:clear
            php artisan optimize